name: 'Setup Python'
description: 'Sets up Python'
inputs:
  python-version: 
    description: 'Version of Python to setup.'
    required: false
    default: '3.11'
runs:
  using: "composite"
  steps:
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}