name: 'Setup Python'
description: 'Sets up Python'
inputs:
  python-version: 
    description: 'Version of Python to setup.'
    required: false
    default: '3.7'
runs:
  using: "composite"
  steps:
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}

    # Suggested by https://stackoverflow.com/a/70431656 - script will complete the setup for pip, since it's incomplete for some versions.
    # - name: Fix PIP (for non-3.6 python)
    #   if: inputs.python-version != 3.6
    #   shell: bash
    #   run: curl -sS https://bootstrap.pypa.io/get-pip.py | python${{ inputs.python-version }}