name: 'Setup Python'
description: 'Sets up python and generic configuration'
runs:
  using: "composite"
  steps:
    - name: Setup Python with Version
      uses: actions/setup-python@v4
      with:
        python-version: '3.11' 