name: 'Test SDK'
description: 'Test SDK using a given test file.'
inputs:
  package-under-test:
    description: 'Path of the package being tested.'
    required: true
  test-dir: 
    description: 'The location of the test file.'
    required: true
  test-file: 
    description: 'The test file to run.'
    required: true
  test-report-dir:
    description: 'The location of the test reports'
    required: true
  python-version: 
    description: 'Version of Python to run tests on.'
    required: true
runs:
  using: "composite"
  steps:
    - uses: actions/download-artifact@v3
    - name: Setup Python
      uses: ./.github/workflows/composite/setup-python
      with:
        python-version: ${{ inputs.python-version }}
    - name: Install package dependencies
      shell: bash
      run: python3 -m pip install -r ${{ inputs.package-under-test }}/requirements.txt

    # FOR DEBUGGING! REMOVE WHEN DONE!
    - name: DEBUGGING
      shell: bash
      run: |
        echo CURL ATTEMPT!
        curl -sS https://bootstrap.pypa.io/get-pip.py | python3.10

        echo PYTHON VERSION!
        python3 -V

        echo PIP LIST!
        python3 -m pip list

    - name: Install package under test
      shell: bash
      run: python3 -m pip install ${{ inputs.package-under-test }}
    - name: Install test dependencies
      shell: bash
      run: pip3 install -r ${{ inputs.test-dir }}/requirements.txt
    - name: Run tests
      shell: bash
      run: |
        cd ${{ inputs.test-dir }}
        python3 ${{ inputs.test-file }}
    - name: Upload Test Results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: Test Results
        path: '${{ inputs.test-report-dir }}/*'