name: 'Test SDK'
description: 'Test SDK using a given test file.'
inputs:
  package-under-test:
    description: 'Path of the package being tested.'
    required: true
  test-dir: 
    description: 'The location of the test file.'
    required: true
  test-file: 
    description: 'The test file to run.'
    required: true
  test-report-dir:
    description: 'The location of the test reports'
    required: true
  python-version: 
    description: 'Version of Python to run tests on.'
    required: true
runs:
  using: "composite"
  steps:
    - uses: actions/download-artifact@v3
    - name: Setup Python
      uses: ./.github/workflows/composite/setup-python
      with:
        python-version: ${{ inputs.python-version }}
    - name: Install package under test
      shell: bash
      run: |
        pip3 install --requirement ${{ inputs.package-under-test }}/requirements.txt
        echo "This will fail. Reason is unknown."
        pip3 install ${{ inputs.package-under-test }}
        echo STUVWXYZ!
    - name: Run tests
      shell: bash
      run: |
        pip3 install --requirement ${{ inputs.test-dir }}/requirements.txt
        cd ${{ inputs.test-dir }}
        python3 ${{ inputs.test-file }}
    - name: Upload Test Results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: Test Results
        path: '${{ inputs.test-report-dir }}/*'