name: 'Test SDK'
description: 'Test SDK using a given test file.'
inputs:
  package-under-test:
    description: 'Path of the package being tested.'
    required: true
  test-dir: 
    description: 'The location of the test file.'
    required: true
  test-file: 
    description: 'The test file to run.'
    required: true
  test-report-dir:
    description: 'The location of the test reports'
    required: true
runs:
  using: "composite"
  steps:
    - uses: actions/download-artifact@v3
    - uses: ./.github/workflows/composite/setup-python
    - name: Install package under test
      shell: bash
      run: |
        pip install --requirement ${{ inputs.package-under-test }}/requirements.txt
        pip install ${{ inputs.package-under-test }}
    - name: Run tests
      shell: bash
      run: |
        pip install --requirement ${{ inputs.test-dir }}/requirements.txt
        cd ${{ inputs.test-dir }}
        python ${{ inputs.test-file }}
    - name: Upload Test Results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: Test Results
        path: '${{ inputs.test-report-dir }}/*'