name: 'Lint SDK'
description: 'Lint SDK from a given directory'
inputs:
  package-name: 
    description: 'Name of the Package to lint.'
    required: true
runs:
  using: "composite"
  steps:
    - uses: actions/download-artifact@v3
    - uses: ./.github/workflows/composite/setup-python
    - name: Run pylint
      shell: bash
      run: |
          pip install pylint
          pip install --requirement ${{ inputs.package-name }}/requirements.txt
          pylint ${{ inputs.package-name }}/*.py -d R,C,W0511