name: 'Lint SDK'
description: 'Lint SDK from a given directory'
inputs:
  package-name: 
    description: 'Name of the Package to lint.'
    required: true
runs:
  using: "composite"
  steps:
    - name: Check out the repo # Checkout to fetch .pylintrc
      uses: actions/checkout@v2
    - name: Download Artifacts
      uses: actions/download-artifact@v2
    - name: Install and run pylint
      shell: bash
      run: |
          sudo apt-get install python3-dev
          pip install pylint
          pip install --requirement ${{ inputs.package-name }}/requirements.txt
          pylint ${{ inputs.package-name }}/*.py -d R,C,W0511