# coding: utf-8

# flake8: noqa

"""
    Tags API

    Tags are case-sensitive key-value pairs that simplify resource management. The Tag Manager API allows you to create and manage such tags to later assign them to related resources in your Bare Metal Cloud (through the respective resource apis) in order to group and categorize them.<br> <br> <span class='pnap-api-knowledge-base-link'> Knowledge base articles to help you can be found <a href='https://phoenixnap.com/kb/bmc-server-management-via-api#server-tag-manager-api' target='_blank'>here</a> </span><br> <br> <b>All URLs are relative to (https://api.phoenixnap.com/tag-manager/v1/)</b> 

    The version of the OpenAPI document: 1.0
    Contact: support@phoenixnap.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "2.0.3"

# import apis into sdk package
from pnap_tag_api.api.tags_api import TagsApi

# import ApiClient
from pnap_tag_api.api_response import ApiResponse
from pnap_tag_api.api_client import ApiClient
from pnap_tag_api.configuration import Configuration
from pnap_tag_api.exceptions import OpenApiException
from pnap_tag_api.exceptions import ApiTypeError
from pnap_tag_api.exceptions import ApiValueError
from pnap_tag_api.exceptions import ApiKeyError
from pnap_tag_api.exceptions import ApiAttributeError
from pnap_tag_api.exceptions import ApiException

# import models into sdk package
from pnap_tag_api.models.delete_result import DeleteResult
from pnap_tag_api.models.error import Error
from pnap_tag_api.models.resource_assignment import ResourceAssignment
from pnap_tag_api.models.tag import Tag
from pnap_tag_api.models.tag_create import TagCreate
from pnap_tag_api.models.tag_update import TagUpdate
