name: (internal) - Build, Lint, Test

on:
  workflow_call:
    inputs:
      package-name:
        required: true
        type: string
      test-file:
        required: true
        type: string

jobs:
  lint:
    name: Lint ${{ inputs.package-name }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/composite/lint-sdk
        with:
          package-name: ${{ inputs.package-name }}
  test:
    name: Test ${{ inputs.package-name }}
    runs-on: ubuntu-latest
    needs:
      - lint
    services:
      mockserver:
        image: mockserver/mockserver:5.13.0
        ports:
          - 1080:1080
    strategy:
      fail-fast: false
      matrix:
        python-version: [ '3.6', '3.11' ]
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/composite/test-sdk
        with:
          package-under-test: ./${{ inputs.package-name }}
          test-dir: tests
          test-file: ${{ inputs.test-file }}
          test-report-dir: tests/test-reports
          python-version: ${{ matrix.python-version }}