name: (abstract) - Build, Lint, Test

on:
  workflow_call:
    inputs:
      package-name:
        required: true
        type: string
      test-file:
        required: true
        type: string
      test-dir:
        required: true
        type: string
      test-report-dir:
        required: true
        type: string

jobs:
  lint:
    name: Lint ${{ inputs.package-name }}
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/composite/lint-sdk
        with:
          package-name: ${{ inputs.package-name }}
  test:
    needs:
      - lint
    uses: ./.github/workflows/_test.yml
    with:
      package-under-test: ./${{ inputs.package-name }}
      test-dir: tests
      test-file: ${{ inputs.test-file }}
      test-report-dir: tests/test-reports
      python-version: ${{ matrix.python-version }}
