name: (abstract) - Generate

on:
  workflow_call:
    inputs:
      spec-link:
        required: true
        type: string
      package-name:
        required: true
        type: string


jobs:
  generate:
    name: Generate ${{ inputs.package-name }}
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/composite/generate-sdk
        with:
          spec-link: ${{ inputs.spec-link }}
          package-name: ${{ inputs.package-name }}