name: (internal) - Publish

on:
  workflow_call:  
    inputs:
      test:
        required: false
        type: boolean
      to_publish:
        required: true
        type: string
    secrets:
      PYPI_API_KEY:
        required: true

jobs:  
  publish-python-gems:
    name: Publish to Python Package Index
    runs-on: ubuntu-18.04
    needs: check-release
    steps:
      - uses: actions/checkout@v3
        with:
            ref: ${{ github.ref }}
      - uses: ./.github/workflows/composite/setup-python
      - name: "Install Dependencies for Packaging"
        run: |
          pip3 install twine
          pip3 install wheel
          pip3 install --requirement ${{ inputs.to_publish }}/requirements.txt
        
      - name: "Build Package"
        run: |
          cd ${{ inputs.to_publish }}
          python3 setup.py sdist bdist_wheel
      - name: "Publish Package"
        if: ${{ !inputs.test }}
        run: |
          cd ${{ needs.check-release.outputs.package }}
          twine upload dist/* -u __token__ -p ${{ secrets.PYPI_API_KEY }}
