name: (internal) - Publish All

on:
  workflow_call:
    inputs:
      test:
        required: false
        type: boolean
    secrets:
      PYPI_API_KEY:
        required: true

jobs:
  publish-audit-api:
    name: Publish Audit API
    uses: ./.github/workflows/_publish.yml
    secrets:
      PYPI_API_KEY: ${{ secrets.PYPI_API_KEY }}
    with:
      test: ${{ inputs.test }}
      to_publish: pnap_audit_api

  publish-bmc-api:
    name: Publish BMC API
    uses: ./.github/workflows/_publish.yml
    secrets:
      PYPI_API_KEY: ${{ secrets.PYPI_API_KEY }}
    with:
      test: ${{ inputs.test }}
      to_publish: pnap_bmc_api

  publish-ip-api:
    name: Publish IP API
    uses: ./.github/workflows/_publish.yml
    secrets:
      PYPI_API_KEY: ${{ secrets.PYPI_API_KEY }}
    with:
      test: ${{ inputs.test }}
      to_publish: pnap_ip_api

  publish-network-api:
    name: Publish Network API
    uses: ./.github/workflows/_publish.yml
    secrets:
      PYPI_API_KEY: ${{ secrets.PYPI_API_KEY }}
    with:
      test: ${{ inputs.test }}
      to_publish: pnap_network_api

  publish-network-storage-api:
    name: Publish Network Storage API
    uses: ./.github/workflows/_publish.yml
    secrets:
      PYPI_API_KEY: ${{ secrets.PYPI_API_KEY }}
    with:
      test: ${{ inputs.test }}
      to_publish: pnap_network_storage_api

  publish-rancher-solution-api:
    name: Publish Rancher Solution API
    uses: ./.github/workflows/_publish.yml
    secrets:
      PYPI_API_KEY: ${{ secrets.PYPI_API_KEY }}
    with:
      test: ${{ inputs.test }}
      to_publish: pnap_rancher_solution_api

  publish-tag-api:
    name: Publish Tag API
    uses: ./.github/workflows/_publish.yml
    secrets:
      PYPI_API_KEY: ${{ secrets.PYPI_API_KEY }}
    with:
      test: ${{ inputs.test }}
      to_publish: pnap_tag_api