name: (abstract) - Publish

on:
  workflow_call:  
    inputs:
      dry_run:
        required: false
        type: boolean
      package_to_publish:
        required: true
        type: string
    secrets:
      PYPI_API_KEY:
        required: true

jobs:  
  publish-python-packages:
    name: Publish ${{ inputs.package_to_publish }} to PyPI
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
            ref: ${{ github.ref }}
      - uses: ./.github/workflows/composite/setup-python
      - name: "Install Dependencies for Packaging"
        run: |
          pip3 install twine
          pip3 install wheel
          pip3 install --requirement ${{ inputs.package_to_publish }}/requirements.txt
        
      - name: "Build Package"
        run: |
          cd ${{ inputs.package_to_publish }}
          python3 setup.py sdist bdist_wheel
      - name: "Publish Package"
        if: ${{ !inputs.dry_run }}
        run: |
          cd ${{ needs.check-release.outputs.package }}
          twine upload dist/* -u __token__ -p ${{ secrets.PYPI_API_KEY }}
