name: (abstract) - Test

on:
  workflow_call:
    inputs:
      package-name:
        required: true
        type: string
      test-file:
        required: true
        type: string

jobs:
  test:
    name: Test ${{ inputs.package-name }} py v ${{ matrix.python-version }}
    runs-on: ubuntu-20.04
    services:
      mockserver:
        image: mockserver/mockserver:5.15.0
        ports:
          - 1080:1080
    strategy:
      fail-fast: false
      matrix:
        python-version: [ '3.7', '3.12' ]
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/composite/test-sdk
        with:
          test-file: ${{ inputs.test-file }}
          package-name: ${{ inputs.package-name }}
