name: Generate workflow
 
on:
  pull_request:
    branches:
      - develop
  schedule:
    - cron: '15 */4 * * *'

jobs:

  generate-bmcapi:
    name: Generate BMC API
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/workflows/composite/generate-sdk
        with:
          spec-link: https://developers.phoenixnap.com/portals/api/sites/phoenixnap-prod-developerportal/liveportal/apis/bmc/download_spec
          package-name: pnap_bmc_api

  generate-ipapi:
    name: Generate IP API
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/workflows/composite/generate-sdk
        with:
          spec-link: https://developers.phoenixnap.com/portals/api/sites/phoenixnap-prod-developerportal/liveportal/apis/ips/download_spec
          package-name: pnap_ip_api

  generate-auditapi:
    name: Generate Audit API
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/workflows/composite/generate-sdk
        with:
          spec-link: https://developers.phoenixnap.com/portals/api/sites/phoenixnap-prod-developerportal/liveportal/apis/bmc-audit/download_spec
          package-name: pnap_audit_api

  generate-networkapi:
    name: Generate Network API
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/workflows/composite/generate-sdk
        with:
          spec-link: https://developers.phoenixnap.com/portals/api/sites/phoenixnap-prod-developerportal/liveportal/apis/networks/download_spec
          package-name: pnap_network_api

  generate-ranchersolutionapi:
    name: Generate Rancher Solution API
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/workflows/composite/generate-sdk
        with:
          spec-link: https://developers.phoenixnap.com/portals/api/sites/phoenixnap-prod-developerportal/liveportal/apis/rancher/download_spec
          package-name: pnap_rancher_solution_api

  generate-tagapi:
    name: Generate Tag API
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/workflows/composite/generate-sdk
        with:
          spec-link: https://developers.phoenixnap.com/portals/api/sites/phoenixnap-prod-developerportal/liveportal/apis/tags/download_spec
          package-name: pnap_tag_api

  push-changes:
    name: Push Changes
    if: startsWith(github.head_ref, 'release') == false && github.head_ref != 'master'  && github.event.pull_request.head.repo.full_name == 'phoenixnap/python-sdk-bmc'
    runs-on: ubuntu-latest
    needs:
      - generate-bmcapi
      - generate-ipapi
      - generate-auditapi
      - generate-networkapi
      - generate-ranchersolutionapi
      - generate-tagapi
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Download Artifacts
        uses: actions/download-artifact@v2
      - name: Add and Commit files
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add -A
          if test "$(git status --porcelain=v1 2>/dev/null | wc -l)" -gt "0" ; then git commit -m "Add changes"; else echo No changes found; fi
      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.event_name == 'schedule' && 'develop' || github.head_ref }}

  lint-bmcapi:
    name: Lint BMC API
    runs-on: ubuntu-latest
    needs:
      - generate-bmcapi
    steps:
      - uses: actions/checkout@v2
      - name: Download Artifacts
        uses: actions/download-artifact@v2
      - uses: ./.github/workflows/composite/lint-sdk
        with:
          package-name: pnap_bmc_api

  lint-ipapi:
    name: Lint IP API
    runs-on: ubuntu-latest
    needs:
      - generate-ipapi
    steps:
      - uses: actions/checkout@v2
      - name: Download Artifacts
        uses: actions/download-artifact@v2
      - uses: ./.github/workflows/composite/lint-sdk
        with:
          package-name: pnap_ip_api

  lint-auditapi:
    name: Lint Audit API
    runs-on: ubuntu-latest
    needs:
      - generate-auditapi
    steps:
      - uses: actions/checkout@v2
      - name: Download Artifacts
        uses: actions/download-artifact@v2
      - uses: ./.github/workflows/composite/lint-sdk
        with:
          package-name: pnap_audit_api

  lint-networkapi:
    name: Lint Network API
    runs-on: ubuntu-latest
    needs:
      - generate-networkapi
    steps:
      - uses: actions/checkout@v2
      - name: Download Artifacts
        uses: actions/download-artifact@v2
      - uses: ./.github/workflows/composite/lint-sdk
        with:
          package-name: pnap_network_api

  lint-ranchersolutionapi:
    name: Lint Rancher Solution API
    runs-on: ubuntu-latest
    needs:
      - generate-ranchersolutionapi
    steps:
      - uses: actions/checkout@v2
      - name: Download Artifacts
        uses: actions/download-artifact@v2
      - uses: ./.github/workflows/composite/lint-sdk
        with:
          package-name: pnap_rancher_solution_api

  lint-tagapi:
    name: Lint Tag API
    runs-on: ubuntu-latest
    needs:
      - generate-tagapi
    steps:
      - uses: actions/checkout@v2
      - name: Download Artifacts
        uses: actions/download-artifact@v2
      - uses: ./.github/workflows/composite/lint-sdk
        with:
          package-name: pnap_tag_api

  test-bmcapi:
    name: Test BMC API
    runs-on: ubuntu-latest
    needs:
      - lint-bmcapi
    services:
      mockserver:
        image: mockserver/mockserver:5.13.0
        ports:
          - 1080:1080
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/workflows/composite/test-sdk
        with:
          package-under-test: ./pnap_bmc_api
          test-dir: tests
          test-file: pnap_bmc_api_test.py
          test-report-dir: tests/test-reports

  test-ipapi:
    name: Test IP API
    runs-on: ubuntu-latest
    needs:
      - lint-ipapi
    services:
      mockserver:
        image: mockserver/mockserver:5.13.0
        ports:
          - 1080:1080
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/workflows/composite/test-sdk
        with:
          package-under-test: ./pnap_ip_api
          test-dir: tests
          test-file: pnap_ip_api_test.py
          test-report-dir: tests/test-reports

  test-auditapi:
    name: Test Audit API
    runs-on: ubuntu-latest
    needs:
      - lint-auditapi
    services:
      mockserver:
        image: mockserver/mockserver:5.13.0
        ports:
          - 1080:1080
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/workflows/composite/test-sdk
        with:
          package-under-test: ./pnap_audit_api
          test-dir: tests
          test-file: pnap_audit_api_test.py
          test-report-dir: tests/test-reports

  test-networkapi:
    name: Test Network API
    runs-on: ubuntu-latest
    needs:
      - lint-networkapi
    services:
      mockserver:
        image: mockserver/mockserver:5.13.0
        ports:
          - 1080:1080
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/workflows/composite/test-sdk
        with:
          package-under-test: ./pnap_network_api
          test-dir: tests
          test-file: pnap_network_api_test.py
          test-report-dir: tests/test-reports

  test-ranchersolutionapi:
    name: Test Rancher Solution API
    runs-on: ubuntu-latest
    needs:
      - lint-ranchersolutionapi
    services:
      mockserver:
        image: mockserver/mockserver:5.13.0
        ports:
          - 1080:1080
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/workflows/composite/test-sdk
        with:
          package-under-test: ./pnap_rancher_solution_api
          test-dir: tests
          test-file: pnap_rancher_solution_api_test.py
          test-report-dir: tests/test-reports

  test-tagapi:
    name: Test Tag API
    runs-on: ubuntu-latest
    needs:
      - lint-tagapi
    services:
      mockserver:
        image: mockserver/mockserver:5.13.0
        ports:
          - 1080:1080
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/workflows/composite/test-sdk
        with:
          package-under-test: ./pnap_tag_api
          test-dir: tests
          test-file: pnap_tag_api_test.py
          test-report-dir: tests/test-reports

  publish-test-results:
    name: Publish Test Results
    needs:
      - test-bmcapi
      - test-ipapi
      - test-auditapi
      - test-networkapi
      - test-ranchersolutionapi
      - test-tagapi
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v2
        with:
          path: test-reports
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        with:
          files: test-reports/**/*.xml
          check_name: "Test Results"
