name: publish-all-sdks-dry-run

on:
  workflow_dispatch:

jobs:
  publish:
    name: (Dry run) Publish All SDKs
    uses: ./.github/workflows/_publish_all.yml
    secrets: 
      PYPI_API_KEY: ${{ secrets.PYPI_API_KEY }}
    with:
      test: true