name: publish-sdk

on:
  release:
    types: [published]

jobs:
  build-and-test-bmcapi:
    uses: ./.github/workflows/_common.yml
    with:
      package-name: pnap_bmc_api
      test-file: pnap_bmc_api.py
  build-and-test-rancherapi:
    uses: ./.github/workflows/_common.yml
    with:
      package-name: pnap_rancher_api
      test-file: pnap_rancher_api.py
  build-and-test-networkapi:
    uses: ./.github/workflows/_common.yml
    with:
      package-name: pnap_network_api
      test-file: pnap_network_api.py
  build-and-test-ipapi:
    uses: ./.github/workflows/_common.yml
    with:
      package-name: pnap_ip_api
      test-file: pnap_ip_api.py
  build-and-test-auditapi:
    uses: ./.github/workflows/_common.yml
    with:
      package-name: pnap_audit_api
      test-file: pnap_audit_api.py
  build-and-test-tagapi:
    uses: ./.github/workflows/_common.yml
    with:
      package-name: pnap_tag_api
      test-file: pnap_tag_api.py
  build-and-test-networkstorageapi:
    uses: ./.github/workflows/_common.yml
    with:
      package-name: pnap_network_storage_api
      test-file: pnap_networkstorage_api.py

  publish:
    name: Publish SDK
    runs-on: ubuntu-latest
    needs:
      - build-and-test-bmcapi
      - build-and-test-rancherapi
      - build-and-test-networkapi
      - build-and-test-ipapi
      - build-and-test-auditapi
      - build-and-test-tagapi
      - build-and-test-networkstorageapi
    uses: ./.github/workflows/_publish.yml
